const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_PATH || 'playwright');
const root=path.resolve(__dirname,'..');
(async()=>{
 const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]);const file=path.join(root,name==='/'?'index.html':name);try{res.setHeader('Content-Type',file.endsWith('.js')?'application/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':'application/octet-stream');res.end(fs.readFileSync(file));}catch{res.writeHead(404);res.end();}});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'chrome'});
 try {
 const page=await browser.newPage({viewport:{width:1280,height:900},serviceWorkers:'block'});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
 await page.route('https://cdn.jsdelivr.net/**',r=>r.abort());
 await page.goto(`http://127.0.0.1:${server.address().port}`);
 await page.getByRole('button',{name:'Nueva obra',exact:true}).click();
 await page.locator('#pName').fill('Obra de prueba');await page.locator('#pClient').fill('Cliente de prueba');
 await page.locator('#pContract').fill('1000');await page.locator('#pCollected').fill('200');await page.locator('#pCost').fill('300');assert.equal(await page.locator('#pProgress').getAttribute('readonly'),'');await page.locator('#saveProjectBtn').click();
 assert.match(await page.locator('#projectsBody').innerText(),/800/);
 await page.locator('[data-edit-project]').click();await page.locator('#pCollected').fill('500');assert.equal(await page.locator('#pProgress').isEditable(),false);await page.locator('#saveProjectBtn').click();
 assert.match(await page.locator('#projectsBody').innerText(),/0%/);
 await page.reload();await page.locator('[data-view="master"]').click();assert.match(await page.locator('#projectsBody').innerText(),/0%/);
 await page.locator('#projectSearch').fill('absent');assert.equal(await page.locator('#projectsBody tr').count(),0);await page.locator('#projectSearch').fill('');
 await page.locator('#addProjectBtn').click();await page.locator('#projectForm button[value="cancel"]').last().click();assert.equal(await page.locator('#projectDialog').evaluate(e=>e.open),false);
 await page.locator('[data-edit-project]').click();assert.equal(await page.locator('#pProgress').isEditable(),false);await page.locator('#projectForm button[value="cancel"]').last().click();
 await page.locator('#addDocumentBtn').click();await page.locator('#dProject').selectOption({index:1});await page.locator('#dTitle').fill('Estimación prueba');await page.locator('#dAmount').fill('250');await page.locator('#dStatus').selectOption('partial');await page.locator('#dSent').selectOption('sent');await page.locator('#documentForm button.primary').click();assert.match(await page.locator('#documentsBody').innerText(),/Pago parcial/);assert.match(await page.locator('#documentsBody').innerText(),/Enviado/);
 await page.locator('[data-view="prices"]').click();await page.locator('#addPriceBtn').click();await page.locator('#prItem').fill('Panel');await page.locator('#prSupplier').fill('Proveedor');await page.locator('#prNet').fill('100');await page.locator('#savePriceBtn').click();assert.match(await page.locator('#pricesBody').innerText(),/116/);
 await page.locator('[data-edit-price]').click();await page.locator('#prNet').fill('200');await page.locator('#savePriceBtn').click();assert.match(await page.locator('#pricesBody').innerText(),/232/);
 await page.locator('[data-view="apu"]').click();const qty=page.locator('[data-apu-field="qty"]').first();await page.locator('[data-apu-field="desc"]').first().fill('Panel de prueba');await qty.fill('12');await page.locator('[data-apu-field="pu"]').first().fill('100');assert.match(await page.locator('#apuDirect').innerText(),/1,200/);await page.locator('#apuSaleUnit').fill('pieza');assert.match(await page.locator('#apuUnit').innerText(),/pieza/);await page.locator('#saveApuInputsBtn').click();assert.match(await page.locator('#apuSaveStatus').innerText(),/Insumos guardados/);
 await page.reload();await page.locator('[data-view="apu"]').click();assert.equal(await page.locator('[data-apu-field="qty"]').first().inputValue(),'12');assert.match(await page.locator('#apuDirect').innerText(),/1,200/);
 await page.locator('[data-view="settings"]').click();await page.locator('#ruleListon').fill('0');await page.locator('#saveRulesBtn').click();assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('rempro_rules_v1')).liston),.61);
 const before=await page.evaluate(()=>localStorage.getItem('rempro_projects_v1'));await page.locator('#importDataInput').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{}')});await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>localStorage.getItem('rempro_projects_v1')),before);
 const downloadPromise=page.waitForEvent('download');await page.locator('#exportDataBtn').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/respaldo/);
 await page.locator('[data-view="master"]').click();await page.locator('[data-remove-project]').click();assert.equal(await page.locator('#projectsBody tr').count(),0);
 await page.setViewportSize({width:390,height:844});await page.locator('#menuBtn').click();await page.locator('[data-view="settings"]').click();assert.equal(await page.locator('#accountBtnSettings').isVisible(),true);
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.waitForTimeout(300);
 await page.screenshot({path:path.join(root,'../mobile-check.png'),fullPage:true});
 const offlineContext = await browser.newContext();
 const offlinePage = await offlineContext.newPage();
 await offlinePage.route('https://cdn.jsdelivr.net/**',r=>r.abort());
 await offlinePage.goto(`http://127.0.0.1:${server.address().port}`);
 await offlinePage.evaluate(async()=>{await navigator.serviceWorker.ready;});
 await offlinePage.reload();
 await offlineContext.setOffline(true);
 await offlinePage.reload();
 await offlinePage.locator('[data-view="master"]').click();
 await offlinePage.locator('#addProjectBtn').click();
 await offlinePage.locator('#pName').fill('Offline'); await offlinePage.locator('#pClient').fill('Test');
 await offlinePage.locator('#pClient').press('Enter');
 assert.match(await offlinePage.locator('#projectsBody').innerText(),/Offline/);
 await offlinePage.reload();await offlinePage.locator('[data-view="master"]').click();
 assert.match(await offlinePage.locator('#projectsBody').innerText(),/Offline/);
 await offlineContext.close();
 assert.deepEqual(errors,[]);console.log('PASS browser: create/edit/reload/filter/cancel/documents/prices/APU/backup/delete/mobile, no uncaught errors');
 } finally {await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
